### ISSUE TITLE
Strip Poets.org vertical

### ISSUE THREAD

**Issue by dustinleblanc** [thinktandem/poets-frontend#233]

**Comment by dustinleblanc** [comment]
https://github.com/thinktandem/poets-api/pull/402 @labboy0276 this was my first stab

**Comment by dbungard** [comment]
## LINK TESTED 
https://pr-245-ds5hwsa-tcynzice66pk2.us-2.platformsh.site/

## Broken Links
All poems tested - examples:
- https://pr-245-ds5hwsa-tcynzice66pk2.us-2.platformsh.site/poem/helen-considers-leaving-troy
- https://pr-245-ds5hwsa-tcynzice66pk2.us-2.platformsh.site/poem/helen-considers-leaving-troy

Additionally, the Poem a Day link is broken from the... 

All poets tested including:
- https://pr-245-ds5hwsa-tcynzice66pk2.us-2.platformsh.site/poet/dorothy-chan
- https://pr-245-ds5hwsa-tcynzice66pk2.us-2.platformsh.site/poet/ladan-osman
- https://pr-245-ds5hwsa-tcynzice66pk2.us-2.platformsh.site/poet/sam-hamill

The entire hero menu.

**Comment by pirog** [comment]
@dbungard @dustinleblanc @labboy0276 FWIW i think a lot  (all?) of the above routes didnt work to begin with eg they dont seem to work in master either.

**Comment by dbungard** [comment]
@pirog @dustinleblanc @labboy0276 
That's what I meant when I said a lot of pages were breaking for me from sometime around 12-2ish on.

**Comment by serundeputy** [comment]
Fixed/removed site verts:
- [x] /poets
- [ ] /poet/{poet-title} ~ we don't have drill down pages for these yet
- [x] /poems
- [x] /poem/{poem-title}
- [x] /audio
- [x] /books
- [x] /book/{book-name}

**Comment by dustinleblanc** [comment]
Some pages for verification:

https://master-7rqtwti-tcynzice66pk2.us-2.platformsh.site/libraries
https://master-7rqtwti-tcynzice66pk2.us-2.platformsh.site/poem-day
https://master-7rqtwti-tcynzice66pk2.us-2.platformsh.site/materials-teachers

https://master-7rqtwti-tcynzice66pk2.us-2.platformsh.site/poems-kids-0 <- NOTE: They need to fix the alias, looks like they have an old page that has the /poems-kids alias that isn't published

**Comment by dbungard** [comment]
This now looks good! Nice work team - closing the ticket.
