### ISSUE TITLE
CORS error from Twitter Library on National Poetry Month

### ISSUE THREAD

**Issue by reynoldsalec** [thinktandem/poets-frontend#305]
When trying to access the National Poetry Month page I'm getting an error:

![Screen Shot 2019-03-26 at 10.12.51 PM.png](https://images.zenhubusercontent.com/5453fc527c6ccc6277a5d40c/38bcb382-a1d6-4f5a-a9e4-168f47068b56)

The console reads

```
Access to fetch at 'https://api.twitter.com/1.1/statuses/user_timeline.json?screen_name=POETSorg&count=4' from origin 'https://master-7rqtwti-tcynzice66pk2.us-2.platformsh.site' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**To Reproduce**

On all environments I tried...

1) Click on the Menu link for "National Poetry Month"
2) See error.

Interestingly, I only get this when clicking on the menu link. Navigating directly to https://master-7rqtwti-tcynzice66pk2.us-2.platformsh.site/national-poetry-month/

### Possible solution
Whitelist all platform and production URLs with Twitter dev/app configuration

**Comment by serundeputy** [comment]
I took a look at this and white listing is not the issue. 

* For example the local lando URLs are already white listed, but the problem exists on local too
* For giggles I tried white listing the p.sh master URL, but problem persists

I put a `.catch` on the twitter API call and that at least fails gracefully, i.e. the page still loads, just sans tweets (as the tweet API call still fails). but does not break the page.

@dustinleblanc how do you feel about not using a `b-link` for the `/national-poetry-month` menu item?

I am open to ideas here.

**Comment by dustinleblanc** [comment]
@dbungard review at https://pr-324-75xng5a-tcynzice66pk2.us-2.platformsh.site/national-poetry-month

You can navigate to the homepage and back via the menu and you'll see the page and tweets render fine.

**Comment by dbungard** [comment]
@dustinleblanc I navigated to the home, to AAP, and then back to NPM and this is what I see (no tweets)
<img width="1242" alt="Screen Shot 2019-04-03 at 8 07 04 AM" src="https://user-images.githubusercontent.com/41634671/55477611-85aca000-55e7-11e9-99f3-cc3f7bcb30b1.png">

I then navigated from NPM to AAP and then to NPM again via the menu and saw the same results.

**Comment by dustinleblanc** [comment]
Fix deploying now

**Comment by dbungard** [comment]
Accessed it from multiple pages - all look good! If AT passes i will merge
