### ISSUE TITLE
Programs page sub-pages have multiple items highlighted "active" in the submenu

### ISSUE THREAD

**Issue by reynoldsalec** [thinktandem/poets-frontend#306]
If you navigate to the Poem-a-day (`/academy-american-poets/programs/poem-day`) or Blaney Lecture (`/academy-american-poets/programs/blaney-lecture`) sub pages, they show both the selected subpage and "programs" highlighted. Selecting "Prizes" (`/academy-american-poets/american-poets-prizes`) does not do this.

<img width="817" alt="Screen Shot 2019-03-26 at 10 24 29 PM" src="https://user-images.githubusercontent.com/1153738/55052381-f8c97b80-5015-11e9-85ba-f4b608a76858.png">

I don't see an active class being explicitly set in our code, so I wonder if this is part of Vue Bootstrap's handling of menu items that it sees have a common root in the URL (in this case, `/academy-american-poets/program`).

**To Reproduce:**

Navigate to https://pr-303-hpc3xfa-tcynzice66pk2.us-2.platformsh.site/academy-american-poets/programs/poem-day (or /academy-american-poets/programs on Master if that PR has been merged)

**Comment by dustinleblanc** [comment]
I think we can just apply https://router.vuejs.org/api/#exact to the third level items

**Comment by dustinleblanc** [comment]
@dbungard as soon as it finishes deploying, you can review at http://pr-327-7tpijhi-tcynzice66pk2.us-2.platformsh.site/academy-american-poets/programs/poem-day

**Comment by dbungard** [comment]
This looks great! If automated tests pass i'll merge and close
